### ISSUE TITLE
[Feature Request] Add ability to load a LUT

### ISSUE THREAD

**Issue by hyuri** [soyersoyer/cameractrls#15]
Hi, it would be great to be able to load a LUT (Look-Up Table) file.

**Comment by soyersoyer** [comment]
What kind of camera do you have? V4L2 doesn't have a control for this yet, but it might be interesting.

**Comment by hyuri** [comment]
Regular laptop webcam. I was thinking it could be applied on top of the webcam feed but I realize now that this would have to be supported by V4L2, otherwise you would have to re-encode the feed + LUT in real-time and maybe even route it to a different output, right? Which sounds impractical for this.

**Comment by soyersoyer** [comment]
I've added #20 for these types of feature requests.

**Comment by hyuri** [comment]
Awesome. Thanks!
