### ISSUE TITLE
"0 camera found"

### ISSUE THREAD

**Issue by Serg10** [soyersoyer/cameractrls#17]
I have a laptop with integrated webcam and a usb cam, both work with browser, telegram, etc... but cameractrls says "0 camera found" 

DELL latitude 7350
Ubuntu 22.04.2 LTS
cameractrls version 0.4.14-0 

![Captura desde 2023-04-12 21-23-12](https://user-images.githubusercontent.com/1223010/231563326-ba6def84-0d76-4e3d-9ba8-743b4a94b4aa.png)

**Comment by soyersoyer** [comment]
Try the `snap connect cameractrls:camera` as described at https://snapcraft.io/cameractrls

**Comment by Serg10** [comment]
Yes, I was using the snap version, but I uninstalled it and installed it via flatpak and everything works fine!

**Comment by asfernandes** [comment]
I have the same problem with snap and flatpak.
How to add a camera manually?
