### ISSUE TITLE
Add resolution and FPS

### ISSUE THREAD

**Issue by sojusnik** [soyersoyer/cameractrls#2]
Would be nice, if you could add an option to select the resolution and FPS of the webcam as well.

**Comment by sojusnik** [comment]
Thank you! I will check it out when there's a more user-friendly way to install your app, f.i. when the flatpak version will be released.

**Comment by soyersoyer** [comment]
What OS do you use?

**Comment by sojusnik** [comment]
Ubuntu 22.04

**Comment by soyersoyer** [comment]
There is a flatpak version, now you can try that! :)

**Comment by soyersoyer** [comment]
The current implementation uses systemd for restoring the values, unfortunately flatpak containers don't have one. A flatpak compatible solution wil be in the v0.5.0.

**Comment by sojusnik** [comment]
BTW, I've played around with the settings and didn't find a way to turn the picture in 90° steps, like from widescreen to portrait. Changing pan and tilt did nothing.

**Comment by soyersoyer** [comment]
Without a real PTZ camera, pan and tilt adjustments are virtual, usually only work when zoomed. Do you have an usb camera? The UVC driver doesn't support the [V4L2_CID_ROTATE](https://elixir.bootlin.com/linux/latest/A/ident/V4L2_CID_ROTATE). I think the USB Video Class lacks rotation. Maybe you can do the same with your capture software.

**Comment by svenstaro** [comment]
Can't this issue be closed as the original request has been fulfilled?

**Comment by sojusnik** [comment]
I think this issue is still open due to:

> The current implementation uses systemd for restoring the values, unfortunately flatpak containers don't have one. A flatpak compatible solution wil be in the v0.5.0.

**Comment by soyersoyer** [comment]
Yes, it can. It is clearer if we have another issue for the flatpak problem.
