### ISSUE TITLE
WARNING:root:V4L2Ctrls: Can't set white_balance_temperature to 3000 ([Errno 84] Invalid or incomplete multibyte or wide character)

### ISSUE THREAD

**Issue by torian257x** [soyersoyer/cameractrls#25]
Does that ring a bell for you? I can set it fine in the gtk

but using cli I get that error:

`$  python3 ~/cameractrls/cameractrls.py  -d "/dev/v4l/by-id/usb-Alpha_Imaging_Tech._Corp._Razer_Kiyo-video-index0" -c white_balance_temperature=3000`

> WARNING:root:V4L2Ctrls: Can't set white_balance_temperature to 3000 ([Errno 84] Invalid or incomplete multibyte or wide character)

**Comment by soyersoyer** [comment]
Yes, white_balance_temperature can only be set when white_balance_auto is off.
The same with cameractrls:
`python3 ~/cameractrls/cameractrls.py  -d /dev/v4l/by-id/usb-Alpha_Imaging_Tech._Corp._Razer_Kiyo-video-index0 -c white_balance_automatic=0,white_balance_temperature=5400`
