### ISSUE TITLE
Package GTK app as Flatpak

### ISSUE THREAD

**Issue by cassidyjames** [soyersoyer/cameractrls#3]
I'd love to use this app, but my work computer is Endless OS and my personal is Fedora Silverblue. As such, apps are typically just installed via Flatpak. Packaging cameractrls as a Flatpak (and ideally distributing via Flathub) would widen its reach to anyone using a modern Linux-based distro, including the image-based ones like Endless OS, Fedora Silverblue, and even Steam OS.

**Comment by soyersoyer** [comment]
Interesting, not as bad as it first seems. I'm in. Stay tuned! :)

**Comment by soyersoyer** [comment]
Could you help me?
I couldn't find a solution for using systemd paths and services, and that is necessary for restoring the control values when you connect the camera/start the session.
There is an issue in flatpak
https://github.com/flatpak/flatpak/issues/2787

**Comment by soyersoyer** [comment]
One possible solution:
- enable webcam access witih --device=all
- map the .config/systemd with --filesystem=xdg-config/systemd
- dbus access to systemd with --socket=system-bus or --socket=session-bus
- write the service file with ExecStart=flatpak run {appid} --command=cameractrls.py -d {device} -c {controls}
- enable the paths/services with dbus systemd

but this seems a bit too much, and the app needs to know whether it's running inside a flatpak or not, so not too ideal.

**Comment by sonnyp** [comment]
> the app needs to know whether it's running inside a flatpak or not

FYI - this is pretty common and not something that's discouraged - libportal even has APIs for it

https://libportal.org/class.Portal.html#type-functions

* `xdp_portal_running_under_flatpak`
* `xdp_portal_running_under_sandbox`
* `xdp_portal_running_under_snap`

**Comment by liquidat** [comment]
Thanks for providing the flatpak - there is discovered this app, and it is awesome!

**Comment by soyersoyer** [comment]
I'm glad you like it

**Comment by cassidyjames** [comment]
I think this can be closed since it's up on Flathub. Thanks for the work, I can now use this for work on Endless OS and Fedora Silverblue!
