### ISSUE TITLE
Lenovo 300 FHD webcam support

### ISSUE THREAD

**Issue by NeuHix** [soyersoyer/cameractrls#33]
Hey! I wanted to change the FOV of this webcam.
But when I start cameractrls, the "basic" section just isn't there.

Is it possible to get the "basic" section of cameractrls for Lenovo 300 FHD Webcam ?

Here's the product I'm talking about: https://www.lenovo.com/in/en/accessories-and-monitors/webcams-and-video/webcams/NET-BO-300-FHD-Webcam/p/GXC1B34793

Here's my Cameractrls for Lenovo 300 FHD webcam which doesn't have the "basic" section.
![image](https://github.com/soyersoyer/cameractrls/assets/94163435/3e25d1c3-e36a-474b-98c0-abac9c5f51ca)

**Comment by soyersoyer** [comment]
Unfortunately, your camera doesn't seem to support changing the FOV.
