### ISSUE TITLE
Flatpak stopped working

### ISSUE THREAD

**Issue by Raki72** [soyersoyer/cameractrls#37]
Hi,

seems the Flatpak version I am using with Nobara 38 stopped working over the weekend. 

Whenever I press the old-fashioned camera button in the UI, I receive a lot of error messages and the camera preview windows does not pop up, as normal:

![cameractrls](https://github.com/soyersoyer/cameractrls/assets/47062002/ca3ccabf-c915-4462-b80d-231b3c0d9a99)

**Comment by soyersoyer** [comment]
Did something happen to your video card driver?

**Comment by soyersoyer** [comment]
Closed due to inactivity. Feel free to open if you need help.
