### ISSUE TITLE
GTK theme dark mode in gtk4 version not detected

### ISSUE THREAD

**Issue by pancaek** [soyersoyer/cameractrls#45]
I stumbled upon this while doing a few tests while running into similar issues to #44 , but since that was related to the gtk3 version I thought I would make a new issue. I can make cameractrls follow the dark mode if I manually set GTK_THEME, but it doesn't follow system settings as the rest of my gtk4 apps do. The gtk3 version still works fine, though. This is using 0.5.15, but I don't see any changes in 0.6,0 that would affect this. (Edit: just confirmed that 0.6.0 also behaves this way)

**Comment by pancaek** [comment]
Strange little bit of additional context, it appears that if I start the gtk3 version first and then also run the gtk4 version while it's running, it picks up the dark mode, but the reverse is not true. If I first start the gtk4 one, the gtk3 one is also light theme.

**Comment by soyersoyer** [comment]
If you run another instance, it will be the same version. (based on the app id)
So now  it sets gtk-application-prefer-dark-theme based on the color-scheme.

**Comment by pancaek** [comment]
It kind of did, the dark theme itself was detected but when using Gradience to modify accent colors, only the standard Gnome blue is used, I don't know those internals well enough to know where those are retrieved from but it's at least kind of there.
