### ISSUE TITLE
[Feature request] - Expand menu for resolution selection or sort by decreasing resolution

### ISSUE THREAD

**Issue by rieje** [soyersoyer/cameractrls#47]
[Feature request] - Expand menu for resolution selection or sort by decreasing resolution. I thought cameractrls didn't support some higher resolutions on my webcam until I realized it didn't show all the resolutions and I can scroll down (pictured is without scrolling down yet for 1280x720 resolution option): https://0x0.st/XibV.jpg

**Comment by soyersoyer** [comment]
Good idea. Fixed in 50c162e02778dfab3a47645662eec36a38048dc1.
Thanks.
