### ISSUE TITLE
Saving presets fails with WARNING:root:ConfigPreset: save_preset failed: name 'readonly' is not defined

### ISSUE THREAD

**Issue by shuhaowu** [soyersoyer/cameractrls#53]
![image](https://github.com/soyersoyer/cameractrls/assets/338100/bacc8347-f5b8-4532-bfe4-7cbbb22a231d)

I'm installed via the source installation. Not sure why this is happening. No settings seems to be saved either.

**Comment by soyersoyer** [comment]
There was a typo in #51, fixed in #52.
