### ISSUE TITLE
`Alt+number` keyboard shortcuts to switch between the tabs

### ISSUE THREAD

**Issue by nekohayo** [soyersoyer/cameractrls#59]
This is a very minor enhancement suggestion, but it would be pretty good for accessibility and convenience: allow switching between the various view tabs (Basic, Exposure, Color, Advanced, Capture) using `Alt+1`, `Alt+2`, etc. like in Nautilus, Calendar, or web browsers :)

**Comment by soyersoyer** [comment]
Hi Jeff, Thanks for this good idea.
