### ISSUE TITLE
Pure black icon color is invisible on black panels

### ISSUE THREAD

**Issue by nekohayo** [soyersoyer/cameractrls#7]
If you use [dash-to-panel](https://extensions.gnome.org/extension/1160/dash-to-panel/), or some other launcher, or other desktop environments than a vanilla GNOME, the icon's colors will prove problematic, as only the small red dot remains visible:

![image](https://user-images.githubusercontent.com/479401/205461368-f408ee86-4c96-46da-bb9a-e24fd05a2365.png)

Generally speaking, pure black does not exist in nature, so it might look more natural if the icon uses some shade of gray, white, subtle gradients or textures.

**Comment by eldelacajita** [comment]
@soyersoyer would you be interested in a new icon that solves this and aligns better with the GNOME/Adwaita style?

I would love to give it a try, no obligation from your side.

**Comment by soyersoyer** [comment]
@nekohayo Good point, thanks for your suggestion.
@eldelacajita Yes, that would be cool :) Please try to preserve the red dot and the simplicity.

**Comment by soyersoyer** [comment]
I added a bloom effect to the current icon, but I still want a GNOME/Adwaita style icon. :)

**Comment by eldelacajita** [comment]
I'm on it!

Here are some first attempts, in two different directions and with slightly different styles.

## Physical camera and sliders representing "settings"
I have used simple shapes, no reflections, no gradients, but some drop shadows.

![Captura desde 2022-12-05 13-44-07](https://user-images.githubusercontent.com/2880679/205640888-1ada0d0b-ef07-464b-8bf6-aad3e6f82177.png)

![Captura desde 2022-12-05 13-37-22](https://user-images.githubusercontent.com/2880679/205640922-e1dd69bb-68b1-457d-a82b-d3afda1806b0.png)

## A different approach, combining the settings icon with a camera
Here I tried a slightly more detailed style, with some gradients and reflections.

![Captura desde 2022-12-05 13-37-30](https://user-images.githubusercontent.com/2880679/205640907-6c3468aa-7f86-4edf-8dc8-e93d7bb8260b.png)

What do you think? Feel free to tell me you want something entirely different, I'm having fun exploring anyway :smile:

**Comment by soyersoyer** [comment]
A not so black icon in v0.4.12. The new with GNOME style is being made. Thanks.
