### ISSUE TITLE
Confused about Save (Fedora + Flatpak)!

### ISSUE THREAD

**Issue by benwilcock** [soyersoyer/cameractrls#9]
Hey! 

Great app, thank you!

Sorry to bother you, but I'm wondering what the trick is to activate the Systemd "Save" button.

I'm on Fedora 37 and using the Flatpak installation method. I have Flatseal and tried opening up file access, but no luck.

Can you help?

Cheers

Ben

**Comment by soyersoyer** [comment]
Sorry, it isn't supported yet. Unfortunately, Flatpak containers can't use Systemd.
I want to create a very small cameractrls daemon in rust to restore the controls, that can be started at startup with [org.freedesktop.portal.Background](https://docs.flatpak.org/en/latest/portal-api-reference.html#gdbus-org.freedesktop.portal.Background).
Stay tuned, it will be in v0.5.

**Comment by benwilcock** [comment]
OK. Cool. Thanks for clarifying. Will await v0.5. Thanks again!

**Comment by hyuri** [comment]
Hi, I'm confused about the question. Is it about having the ability to save the settings with a button — or automatically, as you change the settings? I came here to ask about that.

**Comment by soyersoyer** [comment]
Unfortunately, I haven't finished it yet. Stay tuned :)

**Comment by soyersoyer** [comment]
Fixed in 0.6.0. Save your settings into Preset 1, and enable the Cameractrlsd with Desktop Portal (on Advanced page)
